version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-odoo}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  odoo:
    build:
      context: .
      dockerfile: docker/odoo/Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    working_dir: /opt/odoo
    volumes:
      - ./:/opt/odoo:cached
    ports:
      - "8069:8069"
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=${POSTGRES_USER:-odoo}
      - PGPASSWORD=${POSTGRES_PASSWORD:-odoo}
      - ADMIN_PASS=${ADMIN_PASS:-admin123}

volumes:
  db-data:
